[[0-0 第一个 Kotlin 程序]]

## 获取异常

与绝大多数语言一样， Kotlin 也是用 `try .. catch .. finally ..` 语法进行捕获异常

这种语句的作用是在异常出现时依旧能让程序继续运行

``` kotlin
var info: String? = null

try {
    println(info!!.length)
    println("执行成功")
} catch (e: Exception) {
    println("执行失败")
} finally {
    println("执行完毕")
}

// 无论 try 内语句失败与否，程序将接着运行

```

## 自定义异常

### 通过对异常的继承完成自定义

本例继承的异常类为 `IllegalArgumentException`

``` kotlin
class CustomException : IllegalArgumentException("你这代码写的也太不严谨了")
```

以此方法来完成自定义异常的编写

### 抛出自定义异常

使用 `throw` 进行异常抛出

``` kotlin
  
fun todoTest() {  
  
    var info: String? = null  
  
    try {  
        checkException(info)  
        println(info!!.length)  
        println("执行成功")  
    } catch (e: Exception) {  
        println("执行失败，错误原因：$e")  
    } finally {  
        println("执行完毕")  
    }  
}  
  
fun checkException(str: String?){  
    str ?: throw CustomException()  
}
```

输出

```
执行失败，错误原因：CustomException: 你这代码写的也太不严谨了
执行完毕
```

## 先决条件判断函数

上面代码中的 `checkException` 函数在实际编写中不需要自己写

实际开发过程中可使用 Kotlin 自带的 `checkNotNull` 函数与 `requireNotNull` 函数来判断是否为空并抛出异常

另外还有一种函数 `require` ，该函数接入一个 `Boolean` 值，当该值为 `false` 时会报错